name: S3-Deploy
run-name: deploy-S3
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  s3-job:
    name: deploy-on-s3
    runs-on: ubuntu-latest          # 1. The runner — what machine runs your job

    steps:
      - name: Checkout code         # 2. Pull your repo code onto the runner
        uses: actions/checkout@v4

      - name: Configure AWS creds   # 3. Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1     # change to your bucket's region

      - name: Deploy to S3          # 4. Sync your files to the S3 bucket
        run: aws s3 sync . s3://devallan-newport --delete


        
